tap "4d63/tldr"
tap "beeftornado/rmtree"
tap "dart-lang/dart"
tap "getantibody/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "idleberg/dbxcli"
tap "jesseduffield/lazygit"
tap "nektos/tap"
tap "rigellute/tap"
tap "sachaos/todoist"
tap "sass/sass"
tap "stqp/go-caniuse"
tap "tcnksm/license"
tap "universal-ctags/universal-ctags"
# Search tool like grep, but optimized for programmers
brew "ack"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 3.2
brew "bash-completion"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Remove large files or passwords from Git history like git-filter-branch
brew "bfg"
# Emacs dependency management
brew "cask"
# Control Google Chrome from the command-line
brew "chrome-cli"
# Dependency Manager for PHP
brew "composer"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Interpreted, interactive, object-oriented programming language
brew "python@3.8"
# CLI tool for quick access to files and directories
brew "fasd"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Identify or delete duplicate files
brew "fdupes"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Git extension for versioning large files
brew "git-lfs"
# X.509 and CMS library
brew "libksba"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Bash-tool to store the private data inside a git repo
brew "git-secret"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU version of the tar archiving utility
brew "gnu-tar"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# GitHub Markdown previewer
brew "grip"
# Improved top (interactive process viewer)
brew "htop"
# Add GitHub support to git on the command-line
brew "hub"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Mac App Store command-line interface
brew "mas"
# Modern and intuitive terminal-based text editor
brew "micro"
# Collection of tools that nobody wrote when UNIX was young
brew "moreutils"
# Free (GNU) replacement for the Pico text editor
brew "nano"
# NCurses Disk Usage
brew "ncdu"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# General-purpose scripting language
brew "php"
# Python dependency management tool
brew "pipenv"
# Monitor data's progress through a pipe
brew "pv"
# File browser
brew "ranger"
# Reattach process (e.g., tmux) to background
brew "reattach-to-user-namespace"
# Perl-powered file rename script with many helpful built-ins
brew "rename"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Prints a steam locomotive if you type sl instead of ls
brew "sl"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Spotify daemon
brew "spotifyd"
# Cross-shell prompt for astronauts
brew "starship"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Send macOS User Notifications from the command-line
brew "terminal-notifier"
# Code-search similar to ack
brew "the_silver_searcher"
# Programatically correct mistyped console commands
brew "thefuck"
# Terminal multiplexer
brew "tmux"
# Manage complex tmux sessions easily
brew "tmuxinator"
# CLI tool that moves files or folder to the trash
brew "trash"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Vi 'workalike' with many additional features
brew "vim"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Show the current WiFi network password
brew "wifi-password"
# JavaScript package manager
brew "yarn"
# General-purpose lossless data-compression library
brew "zlib"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Additional completion definitions for zsh
brew "zsh-completions"
# Zsh curses-based tools, e.g. multi-word history searcher
brew "zsh-navigation-tools"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Simplified and community-driven man pages (tldr-pages).
brew "4d63/tldr/tldr"
# The fastest shell plugin manager
brew "getantibody/tap/antibody"
# A command line client for Dropbox built using the Go SDK
brew "idleberg/dbxcli/dbxcli"
# A simple terminal UI for git commands, written in Go
brew "jesseduffield/lazygit/lazygit"
# Run GitHub Actions locally
brew "nektos/tap/act"
# A terminal user interface for Spotify
brew "rigellute/tap/spotify-tui"
# Todoist CLI client
brew "sachaos/todoist/todoist"
# Stylesheet Preprocessor
brew "sass/sass/sass"
# Maintained ctags implementation
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "1password"
cask "1password-cli"
cask "alacritty"
cask "alfred"
cask "archiver"
cask "aware"
cask "bartender"
cask "batteries"
cask "brave-browser"
cask "cheatsheet"
cask "cleanshot"
cask "clockify"
cask "codespace"
cask "cryptomator"
cask "cyberduck"
cask "dash"
cask "discord"
cask "dropbox"
cask "epubquicklook"
cask "figma"
cask "font-anonymous-pro"
cask "font-daddy-time-mono-nerd-font"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-input"
cask "font-meslo-lg"
cask "font-office-code-pro"
cask "font-pt-mono"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "font-source-sans-pro"
cask "fork"
cask "forklift"
cask "gitfiend"
cask "github"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iina"
cask "iterm2"
cask "keycastr"
cask "kitty"
cask "lazy"
cask "malwarebytes"
cask "messenger-unofficial"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "mission-control-plus"
cask "mutify"
cask "nordvpn"
cask "notion"
cask "obs"
cask "open-in-code"
cask "paintbrush"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "qutebrowser"
cask "rectangle"
cask "rocket"
cask "sip"
cask "skype"
cask "slack"
cask "sound-control"
cask "spotify"
cask "suspicious-package"
cask "timche-gmail-desktop"
cask "tiny-player"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "webpquicklook"
cask "yt-music"
mas "Amphetamine", id: 937984704
mas "Binaural", id: 946812450
mas "Dropover", id: 1355679052
mas "Encrypto", id: 935235287
mas "Front and Center", id: 1493996622
mas "GarageBand", id: 682658836
mas "Gestimer", id: 990588172
mas "HazeOver", id: 430798174
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Parcel", id: 639968404
mas "Todoist", id: 585829637
mas "Trello", id: 1278508951
mas "Webcam Settings", id: 533696630
mas "Xcode", id: 497799835
